services:
  investment-agent:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: q_silicon_research_agent
    environment:
      # 加入 OPENROUTER_API_KEY
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - COINGLASS_API_KEY=${COINGLASS_API_KEY}
      - X_BEARER_TOKEN=${X_BEARER_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: "no"
